const pt = {
  appName: 'Izanami',
  appSubName: 'OS',
  loginSubtitle:
    'Izanami é uma plataforma para você criar e compartilhar seus personagens, ' +
    'histórias e livros!',
  loginSubtitleAbove: 'Seja história real, seja rpg.',
  email: 'E-mail',
  emailRequired: 'E-mail é requerido',
  emailInvalid: 'E-mail provido é inválido',
  password: 'Senha',
  passwordRequired: 'Senha é requerido',
  passwordInvalid: 'Senha provida é inválida',
  login: 'Entrar',
  forgotPassword: 'Esqueceu a senha?',
  dontHaveAccount: 'Não possui conta? Cadastre-se.',
  createUserErrorTitle: 'Oops... tivemos um problema ao criar seu usuário',
  loginUserErrorTitle: 'Oops... tivemos um problema ao logar no sistema',
  waitAMinute: 'Aguarde um momento...',
  unexpected: 'Erro inesperado',
  userNotFound: 'O e-mail informado pode não estar cadastrado',
  emailMayBeInvalid: 'O e-mail pode estar inválido',
  shutdown: 'Sair',
  profile: 'Perfil',
  search: 'Pesquisar',
  lore: 'Lore',
  home: 'Feed',
  galery: 'Meus arquivos',
  notifications: 'Alertas',
  character: 'Persona',
  object: 'Objeto',
  ability: 'Habilidade',
  sheet: 'Ficha',
  advanced: 'Avançado',
  session: 'Sessão',
  book: 'Livro',
  name: 'Nome',
  title: 'Título',
  race: 'Raça',
  male: 'Masculino',
  female: 'Feminino',
  other: 'Outro',
  age: 'Idade',
  presentation: 'Apresentação',
  species: 'Espécie',
  origin: 'Origem',
  detail: 'Detalhe',
  details: 'Detalhes',
  noDetails: 'Nenhum detalhe para este personagem',
  history: 'História',
  save: 'Salvar',
  draft: 'Rascunho',
  delete: 'Deletar',
  send: 'Enviar',
  personaNameAndImageRequired: 'Nome e imagem da persona é requerido',
  success: 'Sucesso',
  alreadyHaveAccount: 'Já possui uma conta?',
  signUp: 'Criar conta',
  updateProfile: 'Atualizar perfil',
  firstName: 'Primeiro nome',
  lastName: 'Sobrenome',
  username: 'Nome de usuário',
  nameForUsers: 'Nome para os usuários',
  birthday: 'Data de nascimento',
  usernameInvalid: 'Nome de usuário é requerido',
  updateProfileValidationError:
    'Nome, e-mail, data de nascimento e nome de usuário são obrigatórios',
  sendEmailPassword:
    'Foi enviada uma mensagem para o seu e-mail. Verifique a caixa de span ou lixeira',
  emailDontExists: 'Não existe uma conta com esse e-mail',
};

export default function getStrings() {
  return pt;
}
