const pt = {
  appName: 'Izanami',
  appSubName: 'OS',
  loginSubtitle:
    'Izanami é uma plataforma para você criar e compartilhar seus personagens, ' +
    'histórias e livros!',
  loginSubtitleAbove: 'Seja história real, seja rpg.',
  email: 'Email',
  emailRequired: 'Email is required',
  emailInvalid: 'Email provided is invalid',
  password: 'Password',
  passwordRequired: 'Password is required',
  passwordInvalid: 'Password provided is invalid',
  login: 'Entrar',
  forgotPassword: 'Esqueceu a senha?',
  dontHaveAccount: 'Não possui conta? Cadastre-se.',
  createUserErrorTitle: 'Oops... tivemos um problema ao criar seu usuário',
  loginUserErrorTitle: 'Oops... tivemos um problema ao logar no sistema',
  waitAMinute: 'Wait a minute...',
  unexpected: 'Erro inesperado',
  userNotFound: 'O email informado pode não estar cadastrado',
  shutdown: 'Sair',
  profile: 'Perfil',
  search: 'Pesquisar',
  lore: 'Lore',
  home: 'Feed',
  galery: 'Meus arquivos',
  notifications: 'Alertas',
  character: 'Persona',
  object: 'Objeto',
  ability: 'Habilidade',
  sheet: 'Ficha',
  advanced: 'Avançado',
  session: 'Sessão',
  book: 'Livro',
  name: 'Nome',
  title: 'Título',
  race: 'Raça',
  male: 'Masculino',
  female: 'Feminino',
  other: 'Outro',
  age: 'Idade',
  presentation: 'Apresentação',
};

export default function getStrings() {
  return pt;
}
